### ISSUE TITLE
Get stations by type?

### ISSUE THREAD

**Issue by poldixd** [derhuerst/vbb-stations#5]
Is it possible to get all stations from the S-Bahn or U-Bahn?

**Comment by derhuerst** [comment]
What do you mean "from the S-Bahn or U-Bahn"? Operated by S-Bahn Berlin or by BVG? Or stations with U-Bahn/S-Bahn lines?

**Comment by poldixd** [comment]
I mean all stations operated by BVG like this list: https://de.wikipedia.org/wiki/Liste_der_Berliner_U-Bahnh%C3%B6fe#Stationen

**Comment by derhuerst** [comment]
I don't think there's a machine readable list for that. But since the data doesn't change often, it would be a really nice module! Let me know I you can create one and I will integrate it into `vbb-stations`. 🎉

**Comment by poldixd** [comment]
ok, i try to extract the stations from the gtfs data.

**Comment by derhuerst** [comment]
From the GTFS data you won't get this information. [Everything you can get from there is available in the form of npm modules.](https://github.com/derhuerst/vbb-modules#static-data)

**Comment by poldixd** [comment]
OK. I thought so.

Here are the lists operated by BVG and S-Bahn Berlin GmbH: [poldixd/vbb-stations](https://github.com/poldixd/vbb-stations)

**Comment by derhuerst** [comment]
Great, thanks! 🎉 

To make this easily consumable, It would be nice to have an npm module for that. This would also allow for [semantic versioning](http://semver.org) of the datasets. Also, I'd drop the names from the file to get it more lightweight, as you can get the names from `vbb-stations`.

If you want to keep your repo like this, just tell me! I will write an npm module by myself. 😉

**Comment by poldixd** [comment]
Yes, of course. Please create an npm module. If you find an error, tell me!

**Comment by derhuerst** [comment]
I can either copy the data you compiled or set it up so that it automatically downloads from your repo as a build step. In the seconds case, we'd have only one canonical data source, which is nice, but you'd also have to make sure the URLs don't change too often.

**Comment by poldixd** [comment]
ok, you can automatically download the data so i can add the new stations if they are finished. I don't change the repo name or my username.

**Comment by derhuerst** [comment]
Where do the IDs in your repo come from? They don't seem to match neither the new nor the old IDs.

e.g. Adenauerplatz has `900000023302` (new) and `9023302` (old).

**Comment by poldixd** [comment]
They come directly from the VBB-Rest-API. I make an query each station. But its only the _testing system_. Is the ID in the testing system the old one?


```JSON
{
    "stopLocationOrCoordLocation": [
        {
            "StopLocation": {
                "LocationNotes": {
                    "LocationNote": [

                    ]
                },
                "id": "A=1@O=U Adenauerplatz (Berlin)@X=13307352@Y=52500087@U=86@L=009023302@B=1@V=3.9,@p=1497618658@",
                "extId": "009023302",
                "name": "U Adenauerplatz (Berlin)",
                "lon": 13.307352,
                "lat": 52.500087,
                "weight": 13151,
                "products": 10
            }
        }
    ],
    "serverVersion": "1.7-SNAPSHOT",
    "dialectVersion": "1.23"
}
```

**Comment by poldixd** [comment]
ok, the extId was filled up with zeros in the beginning... But why is your new ID 12 digits long? In 2016 i got an email from the VBB because of an adjustment from 7 to 9 digits.

**Comment by derhuerst** [comment]
I'm not sure, but the mobile API gives me something that I parse to this:

```js
[ { type: 'station',
    name: 'U Adenauerplatz',
    coordinates: { latitude: 52.500087, longitude: 13.307352 },
    id: '900000023302',
    products: 
     { suburban: false,
       subway: true,
       tram: false,
       bus: true,
       ferry: false,
       express: false,
       regional: false } } ]
```

```js
require('vbb-hafas')
.locations('Adenauerplatz', {results: 1, fuzzy: false})
.then(console.log, console.error)
```

**Comment by derhuerst** [comment]
> But why is your new ID 12 digits long? In 2016 i got an email from the VBB because of an adjustment from 7 to 9 digits.

I translate the IDs to the new, long format using [vbb-translate-ids](https://github.com/derhuerst/vbb-translate-ids).

**Comment by poldixd** [comment]
ok, i will think about this. I need this data for my project and i work with the 9 digit system. Sadly, the api from brokenlifts.org is working with the 7 digit system.... http://www.vbb.de/de/broken_lifts.xml

**Comment by derhuerst** [comment]
They said they're planning to fully migrate to the 12-digits system. The GTFS data already has them, the API doesn't :disappointed: (because VBB). So it would make sense for you to migrate to them.

edit: the 12-digits system is the fully international one. afaik this is why they want to migrate to it.

**Comment by derhuerst** [comment]
Another thing I noticed: It might make sense to have a single list of stations. Each stations would have a list of [`agency_id`s from the GTFS](https://vbb-gtfs.jannisr.de/latest/agency.txt). Note that there are stations operated by both BVG & S-Bahn, e.g. Zoologischer Garten (`900000023201`).

edit: This format would allow us to easily add more operators.

**Comment by poldixd** [comment]
ok. It make sence with the 12-digit-system. There is no Mathematical calculation for this? 

Tomorrow i'll create a new list and i merge the two lists. 

The columns:

- id (12 digits)
- station name
- agency_id

**Comment by derhuerst** [comment]
> ok. It make sence with the 12-digit-system. There is no Mathematical calculation for this?

There is, but I haven't fully figured it out. Specific columns are about the country and local entity. See https://de.wikipedia.org/wiki/Internationale_Bahnhofsnummer

**Comment by poldixd** [comment]
hm, ok... I'll convert the ID with your vbb-translate-ids tomorrow...

is this format ok?

```JSON
[
    "900000023201",
    "S+U Zoologischer Garten",
    [
        1,
        796
    ]
],
[
    "900000012345",
    "S Nöldnerplatz",
    [
        1
    ]
],
[
    "900000123456",
    "U Berliner Straße",
    [
        796
    ]
]
```

**Comment by derhuerst** [comment]
> is this format ok?

yes! maybe make the `agency_id`s strings, because you don't know what is going to be used in the CSV file in the future.

**Comment by poldixd** [comment]
So, here is the station list:

https://github.com/poldixd/vbb-stations/blob/master/all-stations-with-operators.json

**Comment by derhuerst** [comment]
❤️ thanks! will adapt [vbb-station-operators](https://github.com/derhuerst/vbb-station-operators).

**Comment by derhuerst** [comment]
Done.
